from pathlib import Path

CREDENTIALS_FILE = Path.home() / ".config" / "pych-client" / "credentials.json"

BASE_URL_ENV = "PYCH_BASE_URL"
DATABASE_ENV = "PYCH_DATABASE"
USERNAME_ENV = "PYCH_USERNAME"
PASSWORD_ENV = "PYCH_PASSWORD"

DEFAULT_BASE_URL = "http://localhost:8123"
DEFAULT_DATABASE = "default"
DEFAULT_USERNAME = "default"
DEFAULT_PASSWORD = ""

DEFAULT_CONNECT_TIMEOUT = 5.0
DEFAULT_READ_WRITE_TIMEOUT = None
